const socket = {

	ADD_USER: "ADD_USER",

	ROOM_USER_JOIN: "ROOM_USER_JOIN",
	ROOM_SEND_MESSENGER: "ROOM_SEND_MESSENGER",
	ROOM_USER_LEAVE: "ROOM_USER_LEAVE",

	USER_SEND_MESSENGER: "USER_SEND_MESSENGER",


}

export default socket